# Generated by Django 4.2.1 on 2025-02-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturefield',
            name='field_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
