# Generated by Django 4.2.1 on 2025-02-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_signaturefield_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturefield',
            name='height',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signaturefield',
            name='width',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
