# Generated by Django 4.2.1 on 2025-02-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signaturefield',
            old_name='height',
            new_name='height_pdf',
        ),
        migrations.RenameField(
            model_name='signaturefield',
            old_name='width',
            new_name='width_pdf',
        ),
        migrations.RenameField(
            model_name='signaturefield',
            old_name='x',
            new_name='x_pdf',
        ),
        migrations.RenameField(
            model_name='signaturefield',
            old_name='y',
            new_name='y_pdf',
        ),
    ]
