# Generated by Django 4.2.1 on 2025-02-11 21:28

from django.db import migrations, models
import signatures.models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='image',
            field=models.ImageField(upload_to=signatures.models.signature_upload_path),
        ),
    ]
